apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: nodejs-ex-image
  labels:
    app: tekton-workshop
spec:
  type: image
  params:
  - name: url
    value: docker://default-route-openshift-image-registry.apps-crc.testing/lab-tekton/nodejs-ex
