apiVersion: operators.coreos.com/v1
kind: CatalogSourceConfig
metadata:
  name: marketplace
  namespace: openshift-marketplace
spec:
  targetNamespace: openshift-operators 
  packages: openshift-pipelines-operator 