

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-operators
spec:
  channel: alpha
  name: openshift-pipelines-operator 
  source: openshift-pipelines-operator 
  sourceNamespace: openshift-operators
